AWS_BUCKET: ""
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""

DB_USERNAME: ""
DB_PASSWORD: ""

COOKIE_SECRET_TOKEN: ""

CMS_USERNAME: ""
CMS_PASSWORD: ""

ADMIN_EMAIL_USERNAME: ""
ADMIN_EMAIL_PW: ""
